### PR TITLE
Implement @stochastic test decorator to report and vary seeds for controlled test nondeterminism.

### PR DESCRIPTION
**Pull request by riastradh-probcomp**
This does not satisfy the goal I had of quantifying relations between

- the test author's intended minimum probability of success for each test, and
- the test executor's desired significance level and statistical power, or threshold for reporting serious bugs vs missing non-serious bugs, &c. (e.g., to distinguish crash tests from quality tests).

I think that for fixed test executor parameters, any given minimum probability of success induces an optimal choice of max runs / min passes.  But we would eventually like to let the executor vary parameters, e.g. for different Jenkins jobs.  So while this will likely help tracking down stochastic failures for now, there is more to be done to quantify the confidence it should give us in the code's correctness.

### CODE REVIEW

**Comment by riastradh-probcomp** [comment]
This should perhaps also be extended to distinguish stochastic *failures* from deterministic failures.  E.g., some assertions should hold always; others only hold for most seeds, say >95% of them.  Crash tests should be able to ignore stochastic failures as long as there are no deterministic ones.

**Comment by gregory-marton** [comment]
And a third class: failures that are stochastic given the same seed, which should fail always.

**Comment by riastradh-probcomp** [comment]
...I don't understand?  Can you elaborate?

**Comment by gregory-marton** [comment]
If a test fails on a given seed, then does not fail on another trial, then that's the wrong kind of stochasticity, and we should catch that, and report it as a failure.

**Comment by riastradh-probcomp** [comment]
I see -- I assume you mean running it twice with the same seed?  Yes, I suppose we could do that too.

**Comment by gregory-marton** [comment]
I don't know how to address the question of whether or not the failure itself is stochastic in nature or just happens only to happen on some fraction of the seeds, but I think we can approach that question by addressing the more important top point: the tester being able to specify the mean and variance of the expected failure rate, and having it report failure rates outside those expectations (including surprising non-failure).

I think this could be done in the context of jenkins by expecting there to be a global database in which you register your current test run. On an individual run, or for the first few hundred runs, you may not be able to tell that something is amiss, but eventually. 

The main issue I see there is versioning. One could use the heuristic that as long as the test method itself didn't change, then you assume it is part of the same test series. That's prone to both kinds of errors: spurious changes and changes not reflected in test, but it's a place to start. Certainly it's easy to implement, and it's easy to reset a series, so at worst such a test would be over-conservative about reporting failures.

What do you think?

**Comment by riastradh-probcomp** [comment]
@axch has some thoughts on the meaningful parameters for the test author and the test executor to vary, which I won't attempt to reproduce in detail here.  Mean and variance aren't really that -- in a Bernoulli trial, the success probability p is the mean, and p*(1 - p) the variance.  But usually I don't know exactly what the success probability is -- I just want to make sure it's at least some minimum.

No particular thoughts on long-term history at the moment.  Sounds like an endeavour to pursue later -- it would require a lot of engineering work to get it integrated reliably.

**Comment by gregory-marton** [comment]
@axch are those thoughts reproduced elsewhere?

**Comment by axch** [comment]
Not yet -- digging myself out from under a heap of other responsibilities.  Writing it up is pretty high on my priority queue; I definitely expect it to be done by the end of next week, but I hope to be able to do it earlier.

**Comment by gregory-marton** [comment]
Alexey published his thoughts on Apr 29 (Friday): http://alexey.radul.name/ideas/2016/on-testing-probabilistic-programs/

**Comment by gregory-marton** [comment]
I think this is a fine first step towards Alexey's larger vision, and works for me as a replacement to flaky. Thanks @riastradh-probcomp !

**Pull request merged**
