### PR TITLE
Use vectorized numpy routines for computing correlation.

### PR DESCRIPTION
**Pull request by riastradh-probcomp**
Avoided this before because we were avoiding a dependency on numpy
before.  It is no longer worthwhile to do so, and calculating
correlations has become a bottleneck for some demonstrations --
which, while in line with our claim that dependence probability and
mutual information are better, does not really do us any favours by
needlessly slowing things down.

This changes the results very slightly, owing to the substitution of
numpy.sum, which does naive accumulated summation, for float_sum,
which does Kahan-Babuska compensated summation.

### CODE REVIEW

**Comment by gregory-marton** [comment]
Please add profile diff to the description? Would also love to see a profile with float_sum.  Thanks!

**Comment by riastradh-probcomp** [comment]
Profile without these changes, total time ~78 sec:
[profile.0.txt](https://github.com/probcomp/bayeslite/files/12714/profile.0.txt)

Profile with just vectorized correlation, total time ~75 sec:
[profile.vcorrel.txt](https://github.com/probcomp/bayeslite/files/12715/profile.vcorrel.txt)

Profile with just vectorized contingency, total time ~29 sec:
[profile.vcontin.txt](https://github.com/probcomp/bayeslite/files/12744/profile.vcontin.txt)

Profile with both vectorizations, total time ~13 sec:
[profile.vboth.txt](https://github.com/probcomp/bayeslite/files/12746/profile.vboth.txt)

So it looks like a ~6x speedup with both changes combined.

**Comment by riastradh-probcomp** [comment]
Profile with float_sum instead of numpy.sum in most places:
[profile.vfs.txt](https://github.com/probcomp/bayeslite/files/12759/profile.vfs.txt)

Using float_sum I get 14.53 +/- .62 sec, and using numpy.sum I get shorter code and 13.39 +/- .26 sec (mean +/- stddev, sampled over seven trials).  Full data:

numpy.sum
13.2074818611
13.3912651539
12.9700360298
13.2240149975
13.4796519279
13.6666970253
13.7974219322

numpy.sum
14.2884509563
13.961835146
13.7663769722
14.1865589619
15.1460089684
15.615844965
14.7712907791

**Comment by gregory-marton** [comment]
That seems like a small enough change in performance that we can continue
to use the safer float_sum.

**Pull request merged**
