### PR TITLE
Pass random seed from BayesDB PRNG into Crosscat.

### PR DESCRIPTION
**Pull request by riastradh-probcomp**
Needed for <https://github.com/probcomp/crosscat/pull/92>.  Requires Crosscat dependency version bump.

### CODE REVIEW

**Comment by gregory-marton** [comment]
Test that crosscat meaningfully "received" the seed?

Can you elaborate on what's still needed for the XXX?

**Comment by riastradh-probcomp** [comment]
XXX comment says what's needed.  Can you elaborate on what you're missing?

**Comment by riastradh-probcomp** [comment]
I assume you're referring to the one in crosscat_seed?

**Comment by gregory-marton** [comment]
Re XXX: a fuller description of the current state, desired state, and e.g. where it's tracked (like an issue id).

**Comment by riastradh-probcomp** [comment]
https://github.com/probcomp/crosscat/issues/93

**Comment by gregory-marton** [comment]
Sorry, I keep forgetting to specify. Whenever I ask for clarification on documentation, I don't mean in this history, I mean in the file itself, for others to read.

**Comment by riastradh-probcomp** [comment]
Yes, I realize that -- I'm just trying to focus on Venture now.

**Pull request merged**
