### PR TITLE
Axch articulated tracing

### PR DESCRIPTION
**Pull request by axch**
Outstanding (potential) problems:
- Could add a test that an unread empty cursor calls finish early
- sql_execute of a query for which results are not expected may leave
  an open tracer for a while (until gc gets the cursor)
- {sql_,}execute of a query from which only one result is requested,
  without fetchall checking that only one is provided, same
- Do we want to permit or suppress multiple calls to "finished" on a
  tracer for a given query? e.g. from multiple calls to fetchone at
  the end, or multiple attempts to iterate?
- Code location: where should the tracing-related classes live?
  Fresh module?

For my part, I am satisfied with status quo, but amenable to changing it.

### CODE REVIEW

**Comment by riastradh-probcomp** [comment]
First immediate reactions:

- What is the motivation for distinguishing all the different stages of tracing?  Do we have an application for that?

- Let's please not discriminate on Python function (or 'arbitrary callable') vs instance of BayesDBTracer.  Just pass in one kind of thing, and invent a name for making a trivial instance of that kind of thing.  (Changing the API of tracing is OK.)

**Comment by riastradh-probcomp** [comment]
Concerning the broader motivation of this, I was under the impression the basic problem we had to solve with tracing was that we want to establish at least two different tracers -- one for session logging, and one for timing, and maybe more for users' purposes --, and the current API allows only one at a time.  However, now I can't find the discussion where that came up, so I'm wondering whether I hallucinated it.

**Comment by axch** [comment]
Re: motivations:
- You are right that we wanted multiple tracers; this change does not address that (but I expect it doesn't impede that either).
- We also wanted tracers that get notified when a query "completes" (not just begins), or when a query triggers an error.
  - The former to write a tracer that prints a nice message about cancelling long queries (which it should refrain from doing if the query in fact finished promptly)
  - The latter to write a tracer that prompts the user to send us their session if we detect that some query encountered an error
- The current state of distinguishing is a consequence of me wanting to understand what the possible stages are, so I could define what it meant for a query to "complete"; having thought that through, there seemed to be no reason to hide the available distinctions.

**Comment by axch** [comment]
Re: discrimination on types: This kind of interface is quite common in the Python community.  In the context of Python, I feel two reasons to keep it:
- I expect clients to be surprised by needing to apply a trivial transformer when they know we could have done this
- It reads to me as offering less cognitive overhead (again, for the Python community): if you just want standard at-start tracing, there is a cognitive fast-path; otherwise, go read the docs of this other thing.

For my part, I prefer e.g., Haskell, where an explicit tag has the community's approval (in addition to being pretty much forced by the type system).

That said, I can change it if you feel strongly.

**Comment by gregory-marton** [comment]
I do think the articulation part is important, independent of having multiple tracers. The application is session capture, which I'd like to integrate promptly, if possible. In its current form, that relies on this articulated tracing.

Re discrimination of types, I'm with @riastradh-probcomp on preference, but weakly. I don't have a good name to suggest.

LGTM.

**Comment by riastradh-probcomp** [comment]
I still don't see why we want anything other than the queries that are passed to q.  It is trivial to add logic to q that does everything I'm aware of our needing:

    def q(bql, params=None):
        record = session_record_begin(bql, params)
        result = cursor_to_df(bdb.execute(bql, params))
        session_record_end(record)

That can

- record every query the user executes via the UI,
- record how long each query took to run, and
- identify queries that never completed.

What else do we need and why?

**Comment by gregory-marton** [comment]
I think having the internal trace will give us more info about the execution path that might have failed, and perhaps why it did so. You're right that we can do minimal session saving in q as you suggest, but for after-the-fact debugging, I think the more info the better.

One concrete thing we can learn better from this more detailed record than from just q is simply the distribution on amounts of time people usually wait before actually cancelling a query. It's certainly not exact, but if we only record query start, we have no hope of learning that.

**Comment by riastradh-probcomp** [comment]
Internal trace: I'm not convinced that the trace of internal queries is likely to be helpful -- in nearly a year of debugging bayeslite, I don't think I have ever used it to find something about an internal query that was not already findable from the stack trace.  I've used the trace for other purposes, e.g. confirming that subqueries in the interleaved execution and compilation are doing the right thing.

Now, I've looked at the *stack* trace many times -- which is something else we could record in q quite easily.  The same is true of interruption, indeed with the same logic:

    def q(bql, params=None):
        record = session_record_begin(bdb, bql, params)
        try:
            df = cursor_to_df(bdb.execute(bql, params))
        except:
            session_record_error(bdb, record)
            raise
        session_record_done(record)
        return df

I don't agree that more info is always better.  For example, a trace of the CPU instructions executed is basically useless to us.  In this case the code is substantially more complex for an application that is not obvious to me.  Once we have a motivating application, then we should reconsider it -- but at the moment I don't see a motivating application.

**Comment by riastradh-probcomp** [comment]
From discussion in person:

- The distribution of timings that @gregory-marton was referring to was to be measured not by explicit timing of cancellation, as I tacitly assumed, but by the time of the last internal query before cancellation, since there ipython gives no guarantee that the kernel even notifies the Python process of cancellation.
- However, it turns out that there are no internal BQL queries in bayeslite anyway, so that's a moot point.
- There are, on the other hand, calls to `bdb.execute` in bdbcontrib that are likely to take a long time, e.g. in mi_hist to plot a histogram of mutual information between two columns across all models.

I think it would be better for user interface operations -- such as interactively drawing an MI histogram plot -- to explicitly make session records like I described in q above -- and I still think q should do that.  I also think we ought to find some way to *ask* ipython to deliver KeyboardInterrupt on cancellation so that we can find a stack trace of where we were when the user got bored, more precisely than the user's query or any hypothetical internal query would tell us.

All that said, as a stop-gap until the user interface itself is more clearly articulated, I don't object to merging this branch (with some small clarifications or fixes), provided we also instrument q itself, wherever that lives, to store session records.

**Pull request merged**
