### PR TITLE
Correct whitespace in crosscat.py sql

### PR DESCRIPTION
**Pull request by alxempirical**
Emacs keeps trying to change this for me, and it's a pain.

### CODE REVIEW

**Comment by riastradh-probcomp** [comment]
How hard is it to tell Emacs to stop trying to change this?

In this case, I would be inclined not to change these particular strings -- they represent the intentionally immutable history of schema changes to the bdb file format.  Maybe changing them in this way won't have any substantive consequences, but I would be reluctant to say that for sure.

**Comment by riastradh-probcomp** [comment]
To amplify the first question: If your Emacs is configured to auto-detect and avoid tabs as indentation in Python source code, then it really shouldn't be modifying string literals.

**Comment by fsaad** [comment]
@riastradh-probcomp why are there tabs in there anyway? Is there a good reason?

**Comment by riastradh-probcomp** [comment]
I probably first edited them in a mode where hitting tab inserted a literal tab character, and then copied & pasted that into the Python strings; then for subsequent edits I probably just mimicked what was already there for consistency.

I'm not saying if we did it again from the beginning we should use a SQL indentation style that involves tabs -- just that changing the intended-immutable schema history now is on somewhat shaky ground, and seems to be motivated by a buggy Emacs thing.

**Comment by fsaad** [comment]
Does our test suite have tests for backward-compatability?

**Comment by riastradh-probcomp** [comment]
I'm not sure there are any automatic tests for Crosscat schema compatibility, but we have a few tests for the bayeslite schema compatibility.

**Comment by gregory-marton** [comment]
Significant whitespace is not part of the SQL standard. What's shaky? 

I'm inclined to normalize to spaces as suggested because we do that elsewhere, regardless of tooling.

**Comment by riastradh-probcomp** [comment]
This causes, for example, `select * from sqlite_master` to yield different results, even for bdb files with nominally exactly the same schema version, even if the select is limited to entities that were part of the bayeslite schema (and not users' tables).

I don't know what specific adverse consequences this may have -- I'm just reluctant to make a cosmetic change that does have non-cosmetic effects in a data storage format.

**Comment by alxempirical** [comment]
Can you give an example where the output from `select * from sqlite_master` changes as a result of whitespace changes?

**Comment by riastradh-probcomp** [comment]
% printf 'create table t( x); select * from sqlite_master;' | sqlite3
    table|t|t|2|CREATE TABLE t( x)
    % printf 'create table t(x); select * from sqlite_master;' | sqlite3 
    table|t|t|2|CREATE TABLE t(x)

I can imagine, e.g., trying to run diff on results out of that, and failing if there are any differences.  (Obviously this is not invariant under all semantics-preserving transformations of SQL, but it is a plausible scenario that one might find oneself in.)

For example, some kind of bayeslite fsck tool might do that to check whether the schema really looks sensible, beyond simply checking the version number.

**Comment by alxempirical** [comment]
My pain point would also be addressed by moving the schema to a submodule, or replacing the tabs with `\t`.

**Comment by riastradh-probcomp** [comment]
No objection to moving it to a submodule.  Replacing tabs by `\t` would substantially detract from readability.

**Comment by alxempirical** [comment]
OK, I'll update the PR.

**Comment by gregory-marton** [comment]
With apologies, I don't think there is substantial risk here, and we're explicitly in a mode where we're allowed to break old things. Agreed re `\t` detracting from readability. Let's just merge.

**Pull request merged**
