### PR TITLE
Document and enforce Crosscat bayeslite serialization format

### PR DESCRIPTION
**Pull request by madeleineth**
@alxempirical and @riastradh-probcomp, can you read over the schema to see if it matches your understanding?

### CODE REVIEW

**Comment by gregory-marton** [comment]
LGTM. @riastradh-probcomp @alxempirical?

**Comment by gregory-marton** [comment]
Rolled back because it broke jenkins tests: 
https://probcomp-4.csail.mit.edu/job/bayeslite-master-crashes/359/console
https://probcomp-4.csail.mit.edu/job/bdbcontrib-tests/150/console

**Comment by riastradh-probcomp** [comment]
Date: Fri, 05 Feb 2016 19:58:10 -0800
   From: Gregory Marton <notifications@github.com>

   Rolled back because it broke jenkins tests: 
   https://probcomp-4.csail.mit.edu/job/bayeslite-master-crashes/359/console
   https://probcomp-4.csail.mit.edu/job/bdbcontrib-tests/150/console

Did it pass check.sh?

**Comment by madeleineth** [comment]
Aside from the test_logging.py issue that fails for me with or without the
patch, yes.

**Pull request merged**
